// <auto-generated />
namespace Bookworm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Firstmigrationsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Firstmigrationsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201710292203524_First migration setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
